steps:
  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: techedServiceKeyCred
    integrationFlowId: <USERID>-flow4
  integrationArtifactGetMplStatus:
    cpiApiServiceKeyCredentialsId: techedServiceKeyCred
    integrationFlowId: <USERID>-flow4
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: techedServiceKeyCred
    integrationFlowId: <USERID>-flow4
    integrationFlowName: <USERID>-flow4
    packageId: CICD
    filePath: <USERID>-flow4.zip
